import { LazyLayersCache, type LazyLayersCacheOptions } from './cache/index.js';
import type { CacheKey } from './types/index.js';
export type { CloudflareInvalidationPublisher } from './cloudflare/invalidationQueue.js';

export function createCache<K extends CacheKey = string, V = unknown>(
  options?: LazyLayersCacheOptions<K, V>,
): LazyLayersCache<K, V> {
  return new LazyLayersCache<K, V>(options);
}

export type {
  CacheStartupOptions,
  SetupCacheOptions,
  SetupRedisOptions,
  SetupCloudflareKVOptions,
} from './setup.js';
export {
  CacheSetupError,
  ManagedLazyLayersCache,
  PRODUCTION_BROADCAST_SET_MAX_BYTES,
  PRODUCTION_INFLIGHT_MAX_ENTRIES,
  PRODUCTION_L1_TTL_MS,
  PRODUCTION_STARTUP_TIMEOUT_MS,
  PRODUCTION_REDIS_COMMAND_TIMEOUT_MS,
  setupCache,
} from './setup.js';

export type {
  BaseInvalidationEvent,
  AtomicPublicationResult,
  AtomicPublishStore,
  CacheEntry,
  CacheCodecOptions,
  CacheKey,
  CacheLevel,
  CacheLevelOptions,
  CacheLoader,
  CacheOptions,
  CacheStore,
  EncodedCacheStore,
  DeleteEvent,
  InflightEntry,
  InflightOptions,
  InflightStore,
  OriginLoadOptions,
  InspectableStore,
  InvalidationEvent,
  InvalidationType,
  KeyInspection,
  PatternEvent,
  SetEvent,
  StoreInspectOptions,
  StoreInspection,
} from './types/index.js';
export { isInspectableStore } from './types/index.js';
export type {
  CacheLayer,
  RedisCapabilityClient,
  RedisCapabilityDiscoveryLimits,
  RedisCapabilityDiscoveryOptions,
  RedisCapabilityManifest,
  RedisCapabilityName,
  RedisCapabilityReason,
  RedisCapabilityState,
  RedisCapabilityStateRecord,
  CircuitBreakerOptions,
  CircuitBreakerState,
  CacheEvent,
  CacheEventHandler,
  DistributedLock,
  DistributedLockOptions,
  HybridCacheOptions,
  HybridCacheResilienceOptions,
  LazyLayersCacheOptions,
  RedisStoreOptions,
  CloudflareKVNamespace,
  CloudflareKVRestOptions,
  CloudflareKVStoreOptions,
  RedisCoreHealth,
  RedisHealthIssue,
  RedisHealthIssueKind,
  RedisInfoClient,
  RedisServerVersion,
  L2OperationGateOptions,
  MemoryBudgetOptions,
  MemoryBudgetSnapshot,
  MemoryCategory,
  MemoryLimit,
  MemoryStoreStats,
} from './cache/index.js';
export {
  CircuitBreaker,
  DistributedLockLostError,
  DistributedLockTimeoutError,
  DEFAULT_CACHE_TTL_MS,
  DEFAULT_INFLIGHT_TTL_MS,
  DEFAULT_INFLIGHT_MAX_ENTRIES,
  DEFAULT_L1_MAX_ENTRIES,
  HybridCache,
  LazyLayersCache,
  OriginLoadClosedError,
  OriginLoadGate,
  OriginLoadOverloadError,
  MemoryStore,
  RedisStore,
  CloudflareKVStore,
  CloudflareKVRestNamespace,
  L2OperationGate,
  L2OperationOverloadError,
  L2OperationTimeoutError,
  L2OperationClosedError,
  RedisPipelineCommandError,
  redisKeyDigest,
  validateRedisPipeline,
  MINIMUM_REDIS_MAJOR_VERSION,
  classifyRedisError,
  getRedisCoreHealth,
  parseRedisServerVersion,
  MemoryBudget,
  getDefaultMemoryBudget,
  resetDefaultMemoryBudget,
  REDIS_CAPABILITY_CLIENT_CONTRACT,
  REDIS_CAPABILITY_COMMANDS,
  DEFAULT_REDIS_CAPABILITY_TIMEOUT_MS,
  DEFAULT_REDIS_CAPABILITY_MAX_COMMAND_NAMES,
  DEFAULT_REDIS_CAPABILITY_MAX_INFO_BYTES,
  DEFAULT_REDIS_CAPABILITY_MAX_COMMAND_REPLY_BYTES,
  MAX_REDIS_CAPABILITY_COMMAND_NAMES,
  MAX_REDIS_CAPABILITY_INFO_BYTES,
  MAX_REDIS_CAPABILITY_COMMAND_REPLY_BYTES,
  discoverRedisCapabilities,
  hasRedisCapability,
  RedisCapabilityRegistry,
  attachRedisReconnectInvalidation,
} from './cache/index.js';
export type { CacheLoggerOptions, CacheRuntimeEnv } from './utils/debugLog.js';
export type { BufferInspection, CacheEncoding, SerializedCacheValue } from './utils/serializer.js';
export {
  CacheSerializationError,
  configureCompression,
  getCompressionTiers,
  LZ4_AVAILABLE,
  NULL_SENTINEL,
  SNAPPY_AVAILABLE,
  ZSTD_AVAILABLE,
  GZIP_MIN_BYTES,
  GZIP_SAVINGS_THRESHOLD,
  deserialize,
  estimateValueBytes,
  getCompressionSavings,
  hasPrefix,
  inspectBuffer,
  serialize,
  serializeWithStats,
  shouldGzip,
  sizeSavings,
  stripPrefix,
} from './utils/serializer.js';
export {
  ALIAS_OBSERVABILITY_ROUTE,
  DEFAULT_OBSERVABILITY_MAX_EVENTS,
  DEFAULT_OBSERVABILITY_MAX_VALUE_BYTES,
  DEFAULT_OBSERVABILITY_PASSWORD,
  DEFAULT_OBSERVABILITY_PORT,
  DEFAULT_OBSERVABILITY_ROUTE,
  DEFAULT_OBSERVABILITY_USERNAME,
  ObservabilityCollector,
  ObservabilityInspector,
  TELEMETRY_CHANNEL_NAME,
  createObservabilityHandler,
  hasTelemetrySubscribers,
  normalizeRoute,
  publishTelemetry,
  renderDashboard,
  renderPrometheus,
  resolveObservabilityOptions,
  startObservabilityServer,
  subscribeTelemetry,
} from './observability/index.js';
export type {
  ConfigSnapshot,
  InspectorDeps,
  ObservabilityAuthOptions,
  ObservabilityCounters,
  ObservabilityHandlerDeps,
  ObservabilityOptions,
  ObservabilityPrometheusOptions,
  ObservabilityRequestHandler,
  ObservabilityServerHandle,
  ObservabilityServerOptions,
  OverviewSnapshot,
  PrometheusGauges,
  RecordedEvent,
  ResolvedObservabilityOptions,
  StartObservabilityServerOptions,
} from './observability/index.js';
export type {
  EventBus,
  EventBusHealth,
  EventBusRetryQueueOptions,
  NatsEventBusHealth,
  NatsEventBusMode,
  NatsEventBusOptions,
  NatsJetStreamOptions,
  RabbitMQEventBusHealth,
  RabbitMQEventBusOptions,
  RedisEventBusHealth,
  RedisEventBusOptions,
} from './event-bus/index.js';
export { NatsEventBus, RabbitMQEventBus, RedisEventBus } from './event-bus/index.js';

export type { CodecName, CompressionMode, CompressionTier, SerializeOptions } from './utils/serializer.js';
